---
- name: vm-windows playbook
  hosts: windows
  gather_facts: no
#  remote_user: i4admin
#  become: true
#  become_user: root
#  become_method: sudo

  roles:
    - role: windows_setup
      tags: windows_setup
    - role: win_dev_tools
      tags: win_dev_tools

