---
- name: Install tfenv
  git:
    repo: https://github.com/tfutils/tfenv.git
    dest: /usr/local/bin/.tfenv
    clone: yes
    update: yes
  become: yes
 
- name: export path
  lineinfile:
    dest: /home/i4admin/.bashrc
    line: export PATH="/usr/local/bin/.tfenv/bin:$PATH"

    #- name: reflect .bash_profile
    #  shell: source /home/i4admin/.bashrc

- name: Install terraform
  shell: |
    /usr/local/bin/.tfenv/bin/tfenv install 1.1.5
    /usr/local/bin/.tfenv/bin/tfenv use 1.1.5
