---
- name: Create internship group
  ansible.builtin.group:
    name: internship
    state: present

- name: Create a login wsl user
  user:
    name: "{{ item.user }}"
    password: "{{ item.password }}"
    groups:
      - internship
    state: present
  with_items:
    - { user: Test.User, password: testtest }
