- name: Add fish repository from PPA and install its signing key.
  apt_repository:
    repo: 'ppa:fish-shell/release-3'
    become: yes

- name: Install fish
  apt:
    name: fish
    update_cache: yes
    state: latest
    become: yes